name: Build

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      # Seems to break the build. Figure this out later.
      #- uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1
        name: Setup Docker BuildKit (buildx)

      - uses: docker/login-action@v1
        name: Login to Github Container Repo
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        name: Generate Docker Metadata
        id: meta
        with:
          images: ghcr.io/SpectrumXYZ/nix

      - uses: docker/build-push-action@v2
        name: Build and Push Docker
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
